# STEP 08 backend -- fit OpenMx to covariance matrices generated by Python.
#
# Usage:
#   Rscript 08_fit_openmx_paired_dirichlet.R INPUT.csv OUTPUT.csv
#
# INPUT contains one row per Dirichlet condition and fixed N. The Python STEP 08
# entry point evaluates the NPE on summaries of these exact same covariance
# matrices, making the comparison paired rather than merely distributional.

args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 2L) {
  stop("Usage: Rscript 08_fit_openmx_paired_dirichlet.R INPUT.csv OUTPUT.csv")
}

input_file  <- normalizePath(args[1L], mustWork = TRUE)
output_file <- normalizePath(args[2L], mustWork = FALSE)

suppressPackageStartupMessages(library(OpenMx))
mxOption(NULL, "Standard Errors", "Yes")
mxOption(NULL, "Calculate Hessian", "Yes")

build_ace_model <- function(obs_mz, obs_dz, n_mz, n_dz) {
  selected <- c("T1", "T2")
  c_mz <- obs_mz[1L, 2L]
  c_dz <- obs_dz[1L, 2L]
  mean_var <- mean(c(diag(obs_mz), diag(obs_dz)))

  start_a <- max(1e-4, 2 * (c_mz - c_dz))
  start_c <- max(1e-4, 2 * c_dz - c_mz)
  start_e <- max(1e-4, mean_var - c_mz)

  var_a <- mxMatrix(
    "Full", 1L, 1L, free = TRUE, values = start_a,
    lbound = 0, label = "VA11", name = "VA"
  )
  var_c <- mxMatrix(
    "Full", 1L, 1L, free = TRUE, values = start_c,
    lbound = 0, label = "VC11", name = "VC"
  )
  var_e <- mxMatrix(
    "Full", 1L, 1L, free = TRUE, values = start_e,
    lbound = 1e-6, label = "VE11", name = "VE"
  )
  total <- mxAlgebra(VA + VC + VE, name = "V")
  parameters <- list(var_a, var_c, var_e, total)

  cov_mz <- mxAlgebra(VA + VC, name = "cMZ")
  expected_mz <- mxAlgebra(
    rbind(cbind(V, cMZ), cbind(t(cMZ), V)), name = "expCovMZ"
  )
  model_mz <- mxModel(
    parameters,
    cov_mz,
    expected_mz,
    mxData(observed = obs_mz, type = "cov", numObs = n_mz),
    mxExpectationNormal(covariance = "expCovMZ", dimnames = selected),
    mxFitFunctionML(),
    name = "MZ"
  )

  cov_dz <- mxAlgebra(0.5 %x% VA + VC, name = "cDZ")
  expected_dz <- mxAlgebra(
    rbind(cbind(V, cDZ), cbind(t(cDZ), V)), name = "expCovDZ"
  )
  model_dz <- mxModel(
    parameters,
    cov_dz,
    expected_dz,
    mxData(observed = obs_dz, type = "cov", numObs = n_dz),
    mxExpectationNormal(covariance = "expCovDZ", dimnames = selected),
    mxFitFunctionML(),
    name = "DZ"
  )

  mxModel(
    "ACEvc",
    parameters,
    mxAlgebra(VA / V, name = "A_std"),
    mxAlgebra(VC / V, name = "C_std"),
    mxAlgebra(VE / V, name = "E_std"),
    model_mz,
    model_dz,
    mxFitFunctionMultigroup(c("MZ", "DZ"))
  )
}

standardized_se <- function(va, vc, ve, vcov_matrix) {
  output <- setNames(rep(NA_real_, 3L), c("A", "C", "E"))
  if (is.null(vcov_matrix) || !is.matrix(vcov_matrix)) return(output)

  total <- va + vc + ve
  if (!is.finite(total) || total <= 0) return(output)
  names_vcov <- rownames(vcov_matrix)
  indices <- match(c("VA11", "VC11", "VE11"), names_vcov)
  if (anyNA(indices)) return(output)

  jacobian <- rbind(
    c(total - va, -va, -va),
    c(-vc, total - vc, -vc),
    c(-ve, -ve, total - ve)
  ) / total^2
  covariance <- jacobian %*%
    vcov_matrix[indices, indices, drop = FALSE] %*%
    t(jacobian)
  setNames(sqrt(pmax(diag(covariance), 0)), c("A", "C", "E"))
}

status_code_for <- function(fit) {
  code <- tryCatch(fit$output$status$code, error = function(e) NULL)
  if (is.null(code) || length(code) != 1L) {
    code <- tryCatch(fit$output$status[[1L]], error = function(e) NA_integer_)
  }
  as.integer(code)
}

paired <- read.csv(input_file, check.names = FALSE)
required <- c(
  "condition_id", "N_pairs", "A_true", "C_true", "E_true",
  "mz_var1", "mz_cov", "mz_var2", "dz_var1", "dz_cov", "dz_var2"
)
missing <- setdiff(required, names(paired))
if (length(missing) > 0L) {
  stop(sprintf("Input is missing columns: %s", paste(missing, collapse = ", ")))
}

fit_one <- function(i) {
  row <- paired[i, , drop = FALSE]
  n_pairs <- as.integer(row$N_pairs)
  dimnames_2 <- list(c("T1", "T2"), c("T1", "T2"))
  observed_mz <- matrix(
    c(row$mz_var1, row$mz_cov, row$mz_cov, row$mz_var2),
    nrow = 2L, byrow = TRUE, dimnames = dimnames_2
  )
  observed_dz <- matrix(
    c(row$dz_var1, row$dz_cov, row$dz_cov, row$dz_var2),
    nrow = 2L, byrow = TRUE, dimnames = dimnames_2
  )

  tryCatch({
    fit <- suppressMessages(mxRun(
      build_ace_model(observed_mz, observed_dz, n_pairs, n_pairs),
      silent = TRUE
    ))
    va <- fit$VA$values[1L, 1L]
    vc <- fit$VC$values[1L, 1L]
    ve <- fit$VE$values[1L, 1L]
    total <- va + vc + ve
    estimates <- c(A = va / total, C = vc / total, E = ve / total)
    ses <- standardized_se(va, vc, ve, fit$output$vcov)
    code <- status_code_for(fit)

    data.frame(
      condition_id = row$condition_id,
      N_pairs = n_pairs,
      A_openmx_est = estimates[["A"]],
      C_openmx_est = estimates[["C"]],
      E_openmx_est = estimates[["E"]],
      A_openmx_se = ses[["A"]],
      C_openmx_se = ses[["C"]],
      E_openmx_se = ses[["E"]],
      openmx_converged = as.integer(isTRUE(code == 0L)),
      openmx_status_code = code,
      openmx_error = "",
      stringsAsFactors = FALSE
    )
  }, error = function(error) {
    data.frame(
      condition_id = row$condition_id,
      N_pairs = n_pairs,
      A_openmx_est = NA_real_, C_openmx_est = NA_real_, E_openmx_est = NA_real_,
      A_openmx_se = NA_real_, C_openmx_se = NA_real_, E_openmx_se = NA_real_,
      openmx_converged = 0L,
      openmx_status_code = NA_integer_,
      openmx_error = conditionMessage(error),
      stringsAsFactors = FALSE
    )
  })
}

results <- vector("list", nrow(paired))
for (i in seq_len(nrow(paired))) {
  results[[i]] <- fit_one(i)
  if (i %% max(1L, floor(nrow(paired) / 20L)) == 0L || i == nrow(paired)) {
    cat(sprintf("OpenMx: %d / %d fits complete\n", i, nrow(paired)))
  }
}

results <- do.call(rbind, results)
dir.create(dirname(output_file), recursive = TRUE, showWarnings = FALSE)
write.csv(results, output_file, row.names = FALSE, na = "")
cat(sprintf(
  "Saved %d OpenMx fits to %s (%.1f%% converged)\n",
  nrow(results), output_file, 100 * mean(results$openmx_converged == 1L)
))
